name: Build Flutter por entorno

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Instalar dependencias
        run: flutter pub get

      - name: Definir entorno según rama
        run: |
          if [ "${GITHUB_REF}" = "refs/heads/main" ]; then
            echo "FLAVOR=production" >> $GITHUB_ENV
            echo "TARGET=lib/main_production.dart" >> $GITHUB_ENV
          else
            echo "FLAVOR=development" >> $GITHUB_ENV
            echo "TARGET=lib/main_development.dart" >> $GITHUB_ENV
          fi

      - name: Build APK (${{ env.FLAVOR }})
        run: flutter build apk --flavor ${{ env.FLAVOR }} -t ${{ env.TARGET }}

      - name: Subir APK como artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-${{ env.FLAVOR }}
          path: build/app/outputs/flutter-apk/app-${{ env.FLAVOR }}-release.apk
